#!/bin/bash
# Usage:
# ink2pdf filename <fontsize>
#
# Supported fontsizes: 8pt, 9pt, 10pt, 11pt, 12pt, 14pt, 17pt or 20pt
# Example:
# ink2pdf exampleFig.svg 14pt

FILENAME="$1"
if [ -z "$2" ]
then
  fontsize="12pt"
else
  fontsize="$2"
fi

echo "Fontsize: $fontsize"
extension="${FILENAME##*.}"
psfile="${FILENAME%.*}.ps"
pstexfile="${FILENAME%.*}.ps_tex"
if [[ "$extension" == "svg" ]]
then
  echo "Converting to ps_tex"
  inkscape --export-ps=$psfile --export-latex --without-gui ${FILENAME}
  FILENAME=$pstexfile
fi

DIR=$(dirname "$FILENAME")
TEXFILEBASE=$(echo $FILENAME | cut -d . -f 1)
TEXFILENOPATH=$(basename "$TEXFILEBASE")
TEXFILE="$TEXFILEBASE.tex"

# Create a temporary standalone tex file
echo "\documentclass[class=extarticle,${fontsize}]{standalone}" >> $TEXFILE
echo "\usepackage{graphicx}" >> $TEXFILE
echo "\usepackage{siunitx}" >> $TEXFILE
echo "\graphicspath{{$DIR/}}" >> $TEXFILE
echo "\usepackage{color}" >> $TEXFILE
echo "\begin{document}" >> $TEXFILE
echo "\def\svgwidth{8cm}" >> $TEXFILE
echo "\input{$FILENAME}" >> $TEXFILE
echo "\end{document}" >> $TEXFILE

# Compile using XeLaTeX
xelatex $TEXFILE
XELATEXRETURN_VAL=$?

# Clean up
rm -f $TEXFILE "$TEXFILENOPATH.aux" "$TEXFILENOPATH.out" "$TEXFILENOPATH.log" "$TEXFILENOPATH.aux"

# Move the pdf file to the correct directory
pdffile="${TEXFILE%.*}".pdf # Contains the path
pdffile=$(basename "$pdffile")
mv $pdffile $DIR
exit $XELATEXRETURN_VAL
