#!/bin/bash

FILENAME="$1"
extension="${FILENAME##*.}"
psfile="${FILENAME%.*}.ps"
pstexfile="${FILENAME%.*}.ps_tex"
if [[ "$extension" == "svg" ]]
then
  echo "Converting to ps_tex"
  inkscape --export-ps=$psfile --export-latex --without-gui ${FILENAME}
  FILENAME=$pstexfile
fi

DIR=$(dirname "$FILENAME")
TEXFILEBASE=$(echo $FILENAME | cut -d . -f 1)
TEXFILENOPATH=$(basename "$TEXFILEBASE")
TEXFILE="$TEXFILEBASE.tex"

# Create a temporary standalone tex file
echo "\documentclass{standalone}" >> $TEXFILE
echo "\usepackage{graphicx}" >> $TEXFILE
echo "\usepackage{siunitx}" >> $TEXFILE
echo "\graphicspath{{$DIR/}}" >> $TEXFILE
echo "\usepackage{color}" >> $TEXFILE
echo "\begin{document}" >> $TEXFILE
echo "\def\svgwidth{8cm}" >> $TEXFILE
echo "\input{$FILENAME}" >> $TEXFILE
echo "\end{document}" >> $TEXFILE

# Compile using XeLaTeX
xelatex $TEXFILE
XELATEXRETURN_VAL=$?

# Clean up
rm -f $TEXFILE "$TEXFILENOPATH.aux" "$TEXFILENOPATH.out" "$TEXFILENOPATH.log" "$TEXFILENOPATH.aux"
exit $XELATEXRETURN_VAL
